---
kind: pipeline
type: kubernetes
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang
  commands:
  - go test
  environment:
    GO111MODULE: on

trigger:
  branch:
  - master

---
kind: pipeline
type: kubernetes
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=amd64 go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8} -X main.build=${DRONE_BUILD_NUMBER}" -a -o build/${DRONE_REPO_NAME}_linux_amd64
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=amd64 go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/${DRONE_REPO_NAME}_linux_amd64
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_TOKEN
    files: release/*
  when:
    event:
    - tag

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: DOCKER_PASSWORD
    repo: ${DRONE_REPO}
    username:
      from_secret: DOCKER_USERNAME
  when:
    event:
    - tag

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
type: kubernetes
name: linux-arm64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm64 go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8} -X main.build=${DRONE_BUILD_NUMBER}" -a -o build/${DRONE_REPO_NAME}_linux_arm64
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm64 go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/${DRONE_REPO_NAME}_linux_arm64
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_TOKEN
    files: release/*
  when:
    event:
    - tag

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: DOCKER_PASSWORD
    repo: ${DRONE_REPO}
    username:
      from_secret: DOCKER_USERNAME
  when:
    event:
    - tag

trigger:
  branch:
  - master

depends_on:
- testing

---
kind: pipeline
type: kubernetes
name: linux-arm

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8} -X main.build=${DRONE_BUILD_NUMBER}" -a -o build/${DRONE_REPO_NAME}_linux_arm
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build
  pull: always
  image: golang
  commands:
  - GOOS=linux GOARCH=arm go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/${DRONE_REPO_NAME}_linux_arm
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_TOKEN
    files: release/*
  when:
    event:
    - tag

- name: publish
  pull: always
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: DOCKER_PASSWORD
    repo: ${DRONE_REPO}
    username:
      from_secret: DOCKER_USERNAME
  when:
    event:
    - tag

trigger:
  branch:
  - master

depends_on:
- testing

...
